# Busca Informada

 Abordagem de busca que utiliza uma função heurística para definir qual sucessor é mais promissor para atingir uma meta (objetivo).

Heurística:
Função h(n) que estima o custo entre o estado atual e os estados gerados a partir dele


# Busca Gulosa

Vamos usar a heurística da Distância de Manhattan, onde dist = |x1 - x2| + |y1 - y2|

## Criando a classe do problema

In [2]:
import numpy as np

class SlidingPuzzle():
    def __init__(self, num_blocos):
        '''
        Construtor
        Args:
            - num_blocos: numero de blocos por linha e coluna, valor inteiro (Ex: 3 significa 3 linhas e 3 colunas)
        '''
        self.num_blocos = num_blocos

    def _encontra_posicao(self, estado, elemento):
        '''
        Varre todo o tabuleiro (estado) e verifica em qual posição 'elemento' está
        Args:
            - estado: matriz contendo o estado do tabuleiro
            - elemento: elemento a ser buscado na matriz
        Return:
            - Retorna a linha e coluna onde o elemento se encontra
        '''
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if estado[i, j] == elemento:
                    return i, j
        return None, None

    def verifica_estados(self, atual, objetivo):
        '''
        Verifica se dois estados são iguais
        Args:
            - atual: matriz que descreve o estado atual
            - objetivo: matriz que descreve o estado objetivo
        Return:
            - booleano dizendo se o estado atual é ou não o objetivo
        '''
        flag = True
        for i in range(self.num_blocos):
            for j in range(self.num_blocos):
                if atual[i, j] != objetivo[i, j]:
                    flag = False
                    break

        return flag

    def expande_estados(self, atual):
        '''
        Dado o estado atual, realiza a expansão de estados
        Args:
            - atual: matriz que descreve o estado atual
        Return:
            - lista com os novos estados após a expansão
        '''
        
        novos_estados = []
        linha, coluna = self._encontra_posicao(atual, 0)

        # Cima
        if linha > 0:
            novo_estado = np.copy(atual)
            nova_linha = linha - 1

            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        # Baixo
        if linha < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_linha = linha + 1

            bloco_alvo = novo_estado[nova_linha, coluna]
            novo_estado[nova_linha, coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)


        # Esquerda
        if coluna > 0:
            novo_estado = np.copy(atual)
            nova_coluna = coluna - 1

            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)

        # Direita
        if coluna < self.num_blocos - 1:
            novo_estado = np.copy(atual)
            nova_coluna = coluna + 1

            bloco_alvo = novo_estado[linha, nova_coluna]
            novo_estado[linha, nova_coluna] = 0
            novo_estado[linha, coluna] = bloco_alvo

            novos_estados.append(novo_estado)
            
        
        return novos_estados
            
    def distancia_Manhattan(self, atual, objetivo):
        '''
        Calcula a distância de Manhattan entre o estado atual e o estado objetivo
        Args: 
            - atual: estado atual do tabuleiro
            - objetivo: estado objetivo do problema
        Return:
            - Distância de Manhattan
        '''
       
       


## Criando a classe de busca

In [4]:
# Fila de prioridade
import heapq

class BuscaGulosa():
    def __init__(self, problema):
        '''
        Construtor
        Args:
            - problema: objeto do problema a ser solucionado
        '''
        
        
    def _verifica_visitado(self, estado, estados_visitados):
        '''
        Verifica se 'estado' está na lista de estados visitados
        Args:
            - estado: estado qualquer do tabuleiro
            - estados_visitados: lista com todos os estados já visitados
        Return:
            - booleano dizendo se o estado foi visitado ou não
        '''
        

    
    def busca(self, inicio, fim):
        '''
        Realiza a busca gulosa, armazenando os estados em uma FILA DE PRIORIDADES
        Args:
            - inicio: estado inicial do problema
            - fim: estado objetivo
        Return:
            - booleano se a solução foi encontrada, lista dos estados visitados, quantidade de estados visitados
        '''
        
        '''
        OBS.: A distância de Manhattan é inversamente proporcional à prioridade, quanto menor a distância, maior
        a prioridade desse estado
        '''
        
        

## Execução

In [5]:
# Criando objeto do problema
problema = SlidingPuzzle(3)

# Criando Matriz inicial e matriz alvo
start = np.matrix([[1,2,0],[8,4,3],[7,6,5]])
target = np.matrix([[1,2,3],[8,0,4],[7,6,5]])

# Mostrando informações iniciais
print(f"Initial state: \n{start}")
print("*"*15)
print(f"Target state: \n{target}")
print("*"*15)

Initial state: 
[[1 2 0]
 [8 4 3]
 [7 6 5]]
***************
Target state: 
[[1 2 3]
 [8 0 4]
 [7 6 5]]
***************


In [ ]:
bg = BuscaGulosa(problema)

bg_solucao, bg_estados_visitados, bg_num_visitados = bg.busca(start, target) # chamando busca

if bg_solucao:
    print("Solução encontrada com ", bg_num_visitados, " passos")
else:
    print("Solução não encontrada!!!")

# Busca A*

    Minimizar o custo de uma busca
    Utiliza o custo até o objetivo h(n) e o custo de cada nó g(n)
    Custo total a ser minimizado -> f(n) = g(n) + h(n)

## Criando a função para usarmos Grafos

In [6]:
class Graph:

    def __init__(self, graph_dict=None, directed=True):
        self.graph_dict = graph_dict or {}
        self.directed = directed
        if not directed:
            self.make_undirected()


    def make_undirected(self):
        for a in list(self.graph_dict.keys()):
            for (b, dist) in self.graph_dict[a].items():
                self.graph_dict.setdefault(b, {})[a] = dist

    def connect(self, A, B, distance=1):
        self.graph_dict.setdefault(A, {})[B] = distance
        if not self.directed:
            self.graph_dict.setdefault(B, {})[A] = distance

    def get(self, a, b=None):
        links = self.graph_dict.setdefault(a, {})
        if b is None:
            return links
        else:
            return links.get(b)

    def nodes(self):
        s1 = set([k for k in self.graph_dict.keys()])
        s2 = set([k2 for v in self.graph_dict.values() for k2, v2 in v.items()])
        nodes = s1.union(s2)
        return list(nodes)

    
class Node:
    def __init__(self, name:str, parent:str):
        self.name = name
        self.parent = parent
        self.g = 0 # Distance to start node
        self.h = 0 # Distance to goal node
        self.f = 0 # Total cost    

    def __eq__(self, other):
        return self.name == other.name
    
    def __lt__(self, other):
         return self.f < other.f
    
    def __repr__(self):
        return ('({0},{1})'.format(self.name, self.f))

    def __hash__(self):
        return hash(self.name)
    

## Populando o grafo

In [7]:
graph = Graph()

graph.connect('SRS', 'Pouso_Alegre', 28.9)
graph.connect('Pouso_Alegre', 'Cambui', 49.1)
graph.connect('Pouso_Alegre', 'Congonhal', 24.3)
graph.connect('Pouso_Alegre', 'Borda', 28.8)
graph.connect('Cambui', 'Camanducaia', 24.7)
graph.connect('Camanducaia', 'Braganca', 60.4)
graph.connect('Braganca', 'Atibaia', 25.2)
graph.connect('Braganca', 'Itapira', 82.4)
graph.connect('Atibaia', 'Campinas', 65.6)
graph.connect('Itapira', 'Campinas', 70.7)
graph.connect('Borda', 'Jacutinga', 57.6)
graph.connect('Jacutinga', 'Itapira', 33.2)
graph.connect('Congonhal', 'Ipuiuna', 24.6)
graph.connect('Ipuiuna', 'Andradas', 67.5)
graph.connect('Andradas', 'ESPinhal', 28.4)
graph.connect('ESPinhal', 'MogiGuacu', 35.7)
graph.connect('MogiGuacu', 'MogiMirim', 25)
graph.connect('MogiMirim', 'Campinas', 60.1)

graph.make_undirected()

heuristics = {}
heuristics['SRS'] = 165
heuristics['Pouso_Alegre'] = 137
heuristics['Cambui'] = 108
heuristics['Camanducaia'] = 97
heuristics['Braganca'] = 54
heuristics['Atibaia'] = 57
heuristics['Campinas'] = 0
heuristics['Borda'] = 117
heuristics['Jacutinga'] = 84
heuristics['Itapira'] = 58
heuristics['Congonhal'] = 135
heuristics['Ipuiuna'] = 139
heuristics['Andradas'] = 106
heuristics['ESPinhal'] = 86
heuristics['MogiGuacu'] = 62
heuristics['MogiMirim'] = 54

## Implementando a função de busca

In [ ]:
import heapq
import numpy as np

def get_path(atual, inicial):
    '''
    Função para gerar o caminho percorrido entre dois estados
    Args:
        - atual: estado atual
        - inicial: estado inicial
    Return:
        - Caminho percorrido entre o estado inicial e final
    '''
   
        

def a_star(grafo, heuristicas, inicio, fim):
    '''
    Algoritmo a*, dado um grafo, um cojunto de heurísticas, um estado/nó inicial e um estado/nó final, 
    busca o caminho ótimo e completo
    Args:
        - grafo: grafo contendo os estados da busca
        - heuristicas: heuristica de cada estado
        - inicio: estado inicial
        - fim: estado final
    Return:
        - Melhor caminho entre estados inicial e final, se a solução foi encontrada, quantidade de estados visitados
    '''
    
    # Criando nó inicial e nó objetivo (não possuem pai)
  
    
     # Inicializando atributos g(0) = 0,  f(0) = 0 + h(0)
   

    

    # Fila de prioridades
   

    # Nós criados
    

    # Nós visitados
    
    
    # Controle
    

    

        # Percorrendo todos os vizinhos do nó atual
        

            # Criando nó com o nome do vizinho e passando o estado atual como pai
            

            # Verificar se a distância pai -> vizinho (g) é menor que 
            # um possível valor (g) do vizinho (caso já tenha sido visitado)

            # caso não haja valor de g para o estado atual a função retorna infinito
            
            
           
                
            # Conectando pai ao novo nó
            

## Executando

In [ ]:
path, solucao, nos_visitados = a_star(graph, heuristics, "SRS", "Campinas")

In [ ]:
print(path)